base_model: tiiuae/Falcon3-10B-Instruct
trust_remote_code: true
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path: abideen/54K_med_spanish_mixed
    type: alpaca
dataset_prepared_path:
val_set_size: 0.001
output_dir: ./outputs/fal

adapter: qlora
lora_model_dir:

sequence_len: 8000
sample_packing:
pad_to_sequence_len: true

lora_r: 32
lora_alpha: 64
lora_dropout: 0.05
lora_target_modules:

  - layers.17.mlp.down_proj
  - layers.6.mlp.down_proj
  - layers.31.mlp.down_proj
  - layers.1.mlp.gate_proj
  - layers.2.mlp.gate_proj
  - layers.3.mlp.gate_proj
  - layers.4.mlp.gate_proj
  - layers.0.mlp.gate_proj
  - layers.25.mlp.gate_proj
  - layers.26.mlp.gate_proj
  - layers.5.mlp.gate_proj
  - layers.24.mlp.gate_proj
  - layers.28.mlp.gate_proj
  - layers.23.mlp.gate_proj
  - layers.27.mlp.gate_proj
  - layers.21.mlp.gate_proj
  - layers.22.mlp.gate_proj
  - layers.29.mlp.gate_proj
  - layers.20.mlp.gate_proj
  - layers.4.mlp.up_proj
  - layers.3.mlp.up_proj
  - layers.0.mlp.up_proj
  - layers.7.mlp.up_proj
  - layers.5.mlp.up_proj
  - layers.6.mlp.up_proj
  - layers.2.mlp.up_proj
  - layers.8.mlp.up_proj
  - layers.1.mlp.up_proj
  - layers.14.mlp.up_proj
  - layers.12.mlp.up_proj
  - layers.9.mlp.up_proj
  - layers.15.mlp.up_proj
  - layers.17.mlp.up_proj
  - layers.13.mlp.up_proj
  - layers.19.mlp.up_proj
  - layers.29.self_attn.k_proj
  - layers.25.self_attn.k_proj
  - layers.23.self_attn.k_proj
  - layers.28.self_attn.k_proj
  - layers.21.self_attn.k_proj
  - layers.19.self_attn.k_proj
  - layers.22.self_attn.k_proj
  - layers.20.self_attn.k_proj
  - layers.24.self_attn.k_proj
  - layers.31.self_attn.k_proj
  - layers.27.self_attn.k_proj
  - layers.26.self_attn.k_proj
  - layers.17.self_attn.k_proj
  - layers.11.self_attn.k_proj
  - layers.14.self_attn.k_proj
  - layers.18.self_attn.k_proj
  - layers.14.self_attn.o_proj
  - layers.7.self_attn.o_proj
  - layers.5.self_attn.o_proj
  - layers.11.self_attn.o_proj
  - layers.6.self_attn.o_proj
  - layers.24.self_attn.o_proj
  - layers.9.self_attn.o_proj
  - layers.13.self_attn.o_proj
  - layers.10.self_attn.o_proj
  - layers.12.self_attn.o_proj
  - layers.8.self_attn.o_proj
  - layers.25.self_attn.o_proj
  - layers.21.self_attn.o_proj
  - layers.23.self_attn.o_proj
  - layers.15.self_attn.o_proj
  - layers.16.self_attn.o_proj
  - layers.8.self_attn.q_proj
  - layers.13.self_attn.q_proj
  - layers.9.self_attn.q_proj
  - layers.14.self_attn.q_proj
  - layers.10.self_attn.q_proj
  - layers.11.self_attn.q_proj
  - layers.0.self_attn.q_proj
  - layers.15.self_attn.q_proj
  - layers.1.self_attn.q_proj
  - layers.6.self_attn.q_proj
  - layers.5.self_attn.q_proj
  - layers.7.self_attn.q_proj
  - layers.12.self_attn.q_proj
  - layers.16.self_attn.q_proj
  - layers.17.self_attn.q_proj
  - layers.26.self_attn.q_proj
  - layers.26.self_attn.v_proj
  - layers.17.self_attn.v_proj
  - layers.3.self_attn.v_proj
  - layers.28.self_attn.v_proj
  - layers.29.self_attn.v_proj
  - layers.21.self_attn.v_proj
  - layers.15.self_attn.v_proj
  - layers.16.self_attn.v_proj
  - layers.20.self_attn.v_proj
  - layers.25.self_attn.v_proj
  - layers.6.self_attn.v_proj
  - layers.23.self_attn.v_proj
  - layers.4.self_attn.v_proj
  - layers.1.self_attn.v_proj
  - layers.14.self_attn.v_proj
  - layers.22.self_attn.v_proj
  - lm.head

lora_target_linear: true
lora_fan_in_fan_out:



gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 1
optimizer: paged_adamw_32bit
lr_scheduler: cosine
learning_rate: 2.0e-5

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 20
evals_per_epoch:
eval_table_size:
saves_per_epoch:
save_strategy:
save_steps:
debug:
deepspeed: deepspeed_configs/zero3.json
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  pad_token: '<|pad|>'
