base_model: Writer/Palmyra-Med-70B-32K
trust_remote_code: true
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path: wasifis/20k-med
    type: alpaca
dataset_prepared_path:
val_set_size: 0.001
output_dir: ./outputs/Palmyra

adapter: qlora
lora_model_dir:

sequence_len: 2000
sample_packing:
pad_to_sequence_len: true

lora_r: 16
lora_alpha: 32
lora_dropout: 0.05
lora_target_modules:
  - model.layers.40.mlp.down_proj
  - model.layers.45.mlp.down_proj
  - model.layers.44.mlp.down_proj
  - model.layers.43.mlp.down_proj
  - model.layers.46.mlp.down_proj
  - model.layers.47.mlp.down_proj
  - model.layers.52.mlp.down_proj
  - model.layers.48.mlp.down_proj
  - model.layers.39.mlp.down_proj
  - model.layers.49.mlp.down_proj
  - model.layers.38.mlp.down_proj
  - model.layers.53.mlp.down_proj
  - model.layers.41.mlp.down_proj
  - model.layers.35.mlp.down_proj
  - model.layers.51.mlp.down_proj
  - model.layers.42.mlp.down_proj
  - model.layers.50.mlp.down_proj
  - model.layers.37.mlp.down_proj
  - model.layers.60.mlp.down_proj
  - model.layers.76.mlp.down_proj
  - model.layers.54.mlp.down_proj
  - model.layers.36.mlp.down_proj
  - model.layers.57.mlp.down_proj
  - model.layers.55.mlp.down_proj
  - model.layers.56.mlp.down_proj
  - model.layers.59.mlp.down_proj
  - model.layers.77.mlp.down_proj
  - model.layers.61.mlp.down_proj
  - model.layers.58.mlp.down_proj
  - model.layers.65.mlp.down_proj
  - model.layers.75.mlp.down_proj
  - model.layers.64.mlp.down_proj
  - model.layers.62.mlp.down_proj
  - model.layers.68.mlp.down_proj
  - model.layers.19.mlp.down_proj
  - model.layers.73.mlp.down_proj
  - model.layers.66.mlp.down_proj
  - model.layers.67.mlp.down_proj
  - model.layers.63.mlp.down_proj
  - model.layers.74.mlp.down_proj
  - model.layers.70.mlp.gate_proj
  - model.layers.71.mlp.gate_proj
  - model.layers.67.mlp.gate_proj
  - model.layers.58.mlp.gate_proj
  - model.layers.55.mlp.gate_proj
  - model.layers.66.mlp.gate_proj
  - model.layers.57.mlp.gate_proj
  - model.layers.56.mlp.gate_proj
  - model.layers.72.mlp.gate_proj
  - model.layers.52.mlp.gate_proj
  - model.layers.54.mlp.gate_proj
  - model.layers.69.mlp.gate_proj
  - model.layers.62.mlp.gate_proj
  - model.layers.74.mlp.gate_proj
  - model.layers.59.mlp.gate_proj
  - model.layers.60.mlp.gate_proj
  - model.layers.68.mlp.gate_proj
  - model.layers.51.mlp.gate_proj
  - model.layers.61.mlp.gate_proj
  - model.layers.53.mlp.gate_proj
  - model.layers.73.mlp.gate_proj
  - model.layers.63.mlp.gate_proj
  - model.layers.48.mlp.gate_proj
  - model.layers.64.mlp.gate_proj
  - model.layers.49.mlp.gate_proj
  - model.layers.50.mlp.gate_proj
  - model.layers.65.mlp.gate_proj
  - model.layers.47.mlp.gate_proj
  - model.layers.44.mlp.gate_proj
  - model.layers.45.mlp.gate_proj
  - model.layers.75.mlp.gate_proj
  - model.layers.46.mlp.gate_proj
  - model.layers.43.mlp.gate_proj
  - model.layers.77.mlp.gate_proj
  - model.layers.41.mlp.gate_proj
  - model.layers.42.mlp.gate_proj
  - model.layers.40.mlp.gate_proj
  - model.layers.32.mlp.gate_proj
  - model.layers.30.mlp.gate_proj
  - model.layers.31.mlp.gate_proj
  - model.layers.70.mlp.up_proj
  - model.layers.67.mlp.up_proj
  - model.layers.69.mlp.up_proj
  - model.layers.66.mlp.up_proj
  - model.layers.62.mlp.up_proj
  - model.layers.63.mlp.up_proj
  - model.layers.65.mlp.up_proj
  - model.layers.68.mlp.up_proj
  - model.layers.71.mlp.up_proj
  - model.layers.64.mlp.up_proj
  - model.layers.61.mlp.up_proj
  - model.layers.59.mlp.up_proj
  - model.layers.58.mlp.up_proj
  - model.layers.57.mlp.up_proj
  - model.layers.55.mlp.up_proj
  - model.layers.72.mlp.up_proj
  - model.layers.54.mlp.up_proj
  - model.layers.56.mlp.up_proj
  - model.layers.73.mlp.up_proj
  - model.layers.60.mlp.up_proj
  - model.layers.51.mlp.up_proj
  - model.layers.50.mlp.up_proj
  - model.layers.53.mlp.up_proj
  - model.layers.74.mlp.up_proj
  - model.layers.52.mlp.up_proj
  - model.layers.49.mlp.up_proj
  - model.layers.30.mlp.up_proj
  - model.layers.47.mlp.up_proj
  - model.layers.34.mlp.up_proj
  - model.layers.46.mlp.up_proj
  - model.layers.48.mlp.up_proj
  - model.layers.38.mlp.up_proj
  - model.layers.45.mlp.up_proj
  - model.layers.43.mlp.up_proj
  - model.layers.29.mlp.up_proj
  - model.layers.75.mlp.up_proj
  - model.layers.42.mlp.up_proj
  - model.layers.35.mlp.up_proj
  - model.layers.44.mlp.up_proj
  - model.layers.31.mlp.up_proj
  - model.layers.72.self_attn.k_proj
  - model.layers.75.self_attn.k_proj
  - model.layers.71.self_attn.k_proj
  - model.layers.74.self_attn.k_proj
  - model.layers.44.self_attn.k_proj
  - model.layers.31.self_attn.k_proj
  - model.layers.33.self_attn.k_proj
  - model.layers.34.self_attn.k_proj
  - model.layers.76.self_attn.k_proj
  - model.layers.78.self_attn.k_proj
  - model.layers.77.self_attn.k_proj
  - model.layers.22.self_attn.k_proj
  - model.layers.18.self_attn.k_proj
  - model.layers.60.self_attn.k_proj
  - model.layers.17.self_attn.k_proj
  - model.layers.56.self_attn.k_proj
  - model.layers.2.self_attn.k_proj
  - model.layers.21.self_attn.k_proj
  - model.layers.23.self_attn.k_proj
  - model.layers.19.self_attn.k_proj
  - model.layers.52.self_attn.k_proj
  - model.layers.35.self_attn.k_proj
  - model.layers.73.self_attn.k_proj
  - model.layers.15.self_attn.k_proj
  - model.layers.27.self_attn.k_proj
  - model.layers.29.self_attn.k_proj
  - model.layers.20.self_attn.k_proj
  - model.layers.28.self_attn.k_proj
  - model.layers.36.self_attn.k_proj
  - model.layers.37.self_attn.k_proj
  - model.layers.25.self_attn.k_proj
  - model.layers.30.self_attn.k_proj
  - model.layers.16.self_attn.k_proj
  - model.layers.32.self_attn.k_proj
  - model.layers.41.self_attn.k_proj
  - model.layers.26.self_attn.k_proj
  - model.layers.68.self_attn.k_proj
  - model.layers.38.self_attn.k_proj
  - model.layers.39.self_attn.k_proj
  - model.layers.70.self_attn.k_proj
  - model.layers.50.self_attn.o_proj
  - model.layers.61.self_attn.o_proj
  - model.layers.46.self_attn.o_proj
  - model.layers.53.self_attn.o_proj
  - model.layers.54.self_attn.o_proj
  - model.layers.19.self_attn.o_proj
  - model.layers.42.self_attn.o_proj
  - model.layers.49.self_attn.o_proj
  - model.layers.41.self_attn.o_proj
  - model.layers.68.self_attn.o_proj
  - model.layers.18.self_attn.o_proj
  - model.layers.45.self_attn.o_proj
  - model.layers.48.self_attn.o_proj
  - model.layers.11.self_attn.o_proj
  - model.layers.64.self_attn.o_proj
  - model.layers.51.self_attn.o_proj
  - model.layers.67.self_attn.o_proj
  - model.layers.13.self_attn.o_proj
  - model.layers.14.self_attn.o_proj
  - model.layers.16.self_attn.o_proj
  - model.layers.17.self_attn.o_proj
  - model.layers.47.self_attn.o_proj
  - model.layers.0.self_attn.o_proj
  - model.layers.20.self_attn.o_proj
  - model.layers.63.self_attn.o_proj
  - model.layers.15.self_attn.o_proj
  - model.layers.5.self_attn.o_proj
  - model.layers.21.self_attn.o_proj
  - model.layers.52.self_attn.o_proj
  - model.layers.12.self_attn.o_proj
  - model.layers.10.self_attn.o_proj
  - model.layers.56.self_attn.o_proj
  - model.layers.62.self_attn.o_proj
  - model.layers.22.self_attn.o_proj
  - model.layers.6.self_attn.o_proj
  - model.layers.43.self_attn.o_proj
  - model.layers.7.self_attn.o_proj
  - model.layers.38.self_attn.o_proj
  - model.layers.9.self_attn.o_proj
  - model.layers.44.self_attn.o_proj
  - model.layers.2.self_attn.q_proj
  - model.layers.4.self_attn.q_proj
  - model.layers.46.self_attn.q_proj
  - model.layers.5.self_attn.q_proj
  - model.layers.7.self_attn.q_proj
  - model.layers.6.self_attn.q_proj
  - model.layers.9.self_attn.q_proj
  - model.layers.10.self_attn.q_proj
  - model.layers.1.self_attn.q_proj
  - model.layers.18.self_attn.q_proj
  - model.layers.62.self_attn.q_proj
  - model.layers.8.self_attn.q_proj
  - model.layers.15.self_attn.q_proj
  - model.layers.14.self_attn.q_proj
  - model.layers.31.self_attn.q_proj
  - model.layers.19.self_attn.q_proj
  - model.layers.16.self_attn.q_proj
  - model.layers.17.self_attn.q_proj
  - model.layers.33.self_attn.q_proj
  - model.layers.35.self_attn.q_proj
  - model.layers.12.self_attn.q_proj
  - model.layers.21.self_attn.q_proj
  - model.layers.27.self_attn.q_proj
  - model.layers.34.self_attn.q_proj
  - model.layers.56.self_attn.q_proj
  - model.layers.13.self_attn.q_proj
  - model.layers.11.self_attn.q_proj
  - model.layers.52.self_attn.q_proj
  - model.layers.54.self_attn.q_proj
  - model.layers.28.self_attn.q_proj
  - model.layers.30.self_attn.q_proj
  - model.layers.20.self_attn.q_proj
  - model.layers.29.self_attn.q_proj
  - model.layers.37.self_attn.q_proj
  - model.layers.75.self_attn.q_proj
  - model.layers.23.self_attn.q_proj
  - model.layers.44.self_attn.q_proj
  - model.layers.32.self_attn.q_proj
  - model.layers.64.self_attn.q_proj
  - model.layers.60.self_attn.q_proj
  - lm.head

lora_target_linear: true
lora_fan_in_fan_out:

wandb_project: qwen-2-wo-8K
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 10
micro_batch_size: 8
num_epochs: 1
optimizer: paged_adamw_32bit
lr_scheduler: cosine
learning_rate: 2.0e-5

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 20
evals_per_epoch:
eval_table_size:
saves_per_epoch:
save_strategy:
save_steps:
debug:
deepspeed: deepspeed_configs/zero3.json
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  pad_token: "<|eot_id|>"
