adapter: qlora
base_model: Qwen/Qwen2.5-72B-Instruct
bf16: auto
dataset_prepared_path: null
datasets:
  - path: wasifis/-Dataset-v8
    type: alpaca
debug: null
deepspeed: deepspeed_configs/zero3.json
early_stopping_patience: null
eval_table_size: null
evals_per_epoch: null
flash_attention: true
fp16: null
fsdp: null
fsdp_config: null
gradient_accumulation_steps: 4
gradient_checkpointing: true
group_by_length: false
learning_rate: 2.0e-05
load_in_4bit: true
load_in_8bit: false
local_rank: null
logging_steps: 1
lora_alpha: 64
lora_dropout: 0.05
lora_fan_in_fan_out: null
lora_model_dir: null
lora_r: 32
lora_target_linear: true
lora_target_modules:
  - layers.62.mlp.down_proj
  - layers.64.mlp.down_proj
  - layers.63.mlp.down_proj
  - layers.66.mlp.down_proj
  - layers.65.mlp.down_proj
  - layers.67.mlp.down_proj
  - layers.68.mlp.down_proj
  - layers.31.mlp.down_proj
  - layers.60.mlp.down_proj
  - layers.69.mlp.down_proj
  - layers.61.mlp.down_proj
  - layers.59.mlp.down_proj
  - layers.70.mlp.down_proj
  - layers.30.mlp.down_proj
  - layers.32.mlp.down_proj
  - layers.34.mlp.down_proj
  - layers.76.mlp.down_proj
  - layers.33.mlp.down_proj
  - layers.72.mlp.down_proj
  - layers.58.mlp.down_proj
  - layers.71.mlp.down_proj
  - layers.75.mlp.down_proj
  - layers.56.mlp.down_proj
  - layers.29.mlp.down_proj
  - layers.26.mlp.down_proj
  - layers.35.mlp.down_proj
  - layers.28.mlp.down_proj
  - layers.57.mlp.down_proj
  - layers.77.mlp.down_proj
  - layers.36.mlp.down_proj
  - layers.27.mlp.down_proj
  - layers.78.mlp.down_proj
  - layers.25.mlp.down_proj
  - layers.73.mlp.down_proj
  - layers.37.mlp.down_proj
  - layers.55.mlp.down_proj
  - layers.74.mlp.down_proj
  - layers.54.mlp.down_proj
  - layers.53.mlp.down_proj
  - layers.24.mlp.down_proj
  - layers.78.mlp.gate_proj
  - layers.77.mlp.gate_proj
  - layers.76.mlp.gate_proj
  - layers.79.mlp.gate_proj
  - layers.75.mlp.gate_proj
  - layers.74.mlp.gate_proj
  - layers.73.mlp.gate_proj
  - layers.72.mlp.gate_proj
  - layers.71.mlp.gate_proj
  - layers.70.mlp.gate_proj
  - layers.69.mlp.gate_proj
  - layers.57.mlp.gate_proj
  - layers.54.mlp.gate_proj
  - layers.55.mlp.gate_proj
  - layers.68.mlp.gate_proj
  - layers.63.mlp.gate_proj
  - layers.53.mlp.gate_proj
  - layers.44.mlp.gate_proj
  - layers.45.mlp.gate_proj
  - layers.46.mlp.gate_proj
  - layers.58.mlp.gate_proj
  - layers.49.mlp.gate_proj
  - layers.56.mlp.gate_proj
  - layers.67.mlp.gate_proj
  - layers.62.mlp.gate_proj
  - layers.50.mlp.gate_proj
  - layers.64.mlp.gate_proj
  - layers.52.mlp.gate_proj
  - layers.43.mlp.gate_proj
  - layers.66.mlp.gate_proj
  - layers.48.mlp.gate_proj
  - layers.40.mlp.gate_proj
  - layers.47.mlp.gate_proj
  - layers.61.mlp.gate_proj
  - layers.59.mlp.gate_proj
  - layers.65.mlp.gate_proj
  - layers.60.mlp.gate_proj
  - layers.42.mlp.gate_proj
  - layers.51.mlp.gate_proj
  - layers.37.mlp.gate_proj
  - layers.70.mlp.up_proj
  - layers.69.mlp.up_proj
  - layers.71.mlp.up_proj
  - layers.68.mlp.up_proj
  - layers.72.mlp.up_proj
  - layers.67.mlp.up_proj
  - layers.66.mlp.up_proj
  - layers.73.mlp.up_proj
  - layers.46.mlp.up_proj
  - layers.75.mlp.up_proj
  - layers.63.mlp.up_proj
  - layers.74.mlp.up_proj
  - layers.76.mlp.up_proj
  - layers.62.mlp.up_proj
  - layers.45.mlp.up_proj
  - layers.64.mlp.up_proj
  - layers.65.mlp.up_proj
  - layers.44.mlp.up_proj
  - layers.53.mlp.up_proj
  - layers.47.mlp.up_proj
  - layers.49.mlp.up_proj
  - layers.57.mlp.up_proj
  - layers.48.mlp.up_proj
  - layers.42.mlp.up_proj
  - layers.43.mlp.up_proj
  - layers.56.mlp.up_proj
  - layers.61.mlp.up_proj
  - layers.54.mlp.up_proj
  - layers.40.mlp.up_proj
  - layers.60.mlp.up_proj
  - layers.55.mlp.up_proj
  - layers.77.mlp.up_proj
  - layers.41.mlp.up_proj
  - layers.35.mlp.up_proj
  - layers.37.mlp.up_proj
  - layers.58.mlp.up_proj
  - layers.34.mlp.up_proj
  - layers.36.mlp.up_proj
  - layers.38.mlp.up_proj
  - layers.33.mlp.up_proj
  - layers.36.self_attn.k_proj
  - layers.79.self_attn.k_proj
  - layers.35.self_attn.k_proj
  - layers.34.self_attn.k_proj
  - layers.37.self_attn.k_proj
  - layers.33.self_attn.k_proj
  - layers.38.self_attn.k_proj
  - layers.39.self_attn.k_proj
  - layers.74.self_attn.k_proj
  - layers.77.self_attn.k_proj
  - layers.41.self_attn.k_proj
  - layers.69.self_attn.k_proj
  - layers.78.self_attn.k_proj
  - layers.32.self_attn.k_proj
  - layers.30.self_attn.k_proj
  - layers.70.self_attn.k_proj
  - layers.25.self_attn.k_proj
  - layers.42.self_attn.k_proj
  - layers.29.self_attn.k_proj
  - layers.31.self_attn.k_proj
  - layers.68.self_attn.k_proj
  - layers.66.self_attn.k_proj
  - layers.22.self_attn.k_proj
  - layers.44.self_attn.k_proj
  - layers.65.self_attn.k_proj
  - layers.40.self_attn.k_proj
  - layers.63.self_attn.k_proj
  - layers.23.self_attn.k_proj
  - layers.28.self_attn.k_proj
  - layers.24.self_attn.k_proj
  - layers.26.self_attn.k_proj
  - layers.67.self_attn.k_proj
  - layers.75.self_attn.k_proj
  - layers.27.self_attn.k_proj
  - layers.57.self_attn.k_proj
  - layers.64.self_attn.k_proj
  - layers.71.self_attn.k_proj
  - layers.61.self_attn.k_proj
  - layers.72.self_attn.k_proj
  - layers.73.self_attn.k_proj
  - layers.69.self_attn.o_proj
  - layers.39.self_attn.o_proj
  - layers.16.self_attn.o_proj
  - layers.14.self_attn.o_proj
  - layers.19.self_attn.o_proj
  - layers.42.self_attn.o_proj
  - layers.12.self_attn.o_proj
  - layers.15.self_attn.o_proj
  - layers.17.self_attn.o_proj
  - layers.23.self_attn.o_proj
  - layers.38.self_attn.o_proj
  - layers.22.self_attn.o_proj
  - layers.13.self_attn.o_proj
  - layers.29.self_attn.o_proj
  - layers.41.self_attn.o_proj
  - layers.44.self_attn.o_proj
  - layers.46.self_attn.o_proj
  - layers.45.self_attn.o_proj
  - layers.49.self_attn.o_proj
  - layers.43.self_attn.o_proj
  - layers.30.self_attn.o_proj
  - layers.26.self_attn.o_proj
  - layers.25.self_attn.o_proj
  - layers.37.self_attn.o_proj
  - layers.47.self_attn.o_proj
  - layers.11.self_attn.o_proj
  - layers.18.self_attn.o_proj
  - layers.28.self_attn.o_proj
  - layers.20.self_attn.o_proj
  - layers.27.self_attn.o_proj
  - layers.52.self_attn.o_proj
  - layers.53.self_attn.o_proj
  - layers.35.self_attn.o_proj
  - layers.71.self_attn.o_proj
  - layers.10.self_attn.o_proj
  - layers.3.self_attn.o_proj
  - layers.21.self_attn.o_proj
  - layers.24.self_attn.o_proj
  - layers.68.self_attn.o_proj
  - layers.48.self_attn.o_proj
  - layers.1.self_attn.q_proj
  - layers.2.self_attn.q_proj
  - layers.3.self_attn.q_proj
  - layers.0.self_attn.q_proj
  - layers.5.self_attn.q_proj
  - layers.4.self_attn.q_proj
  - layers.6.self_attn.q_proj
  - layers.8.self_attn.q_proj
  - layers.7.self_attn.q_proj
  - layers.9.self_attn.q_proj
  - layers.10.self_attn.q_proj
  - layers.68.self_attn.q_proj
  - layers.25.self_attn.q_proj
  - layers.12.self_attn.q_proj
  - layers.54.self_attn.q_proj
  - layers.55.self_attn.q_proj
  - layers.61.self_attn.q_proj
  - layers.18.self_attn.q_proj
  - layers.72.self_attn.q_proj
  - layers.66.self_attn.q_proj
  - layers.49.self_attn.q_proj
  - layers.11.self_attn.q_proj
  - layers.52.self_attn.q_proj
  - layers.64.self_attn.q_proj
  - layers.53.self_attn.q_proj
  - layers.15.self_attn.q_proj
  - layers.50.self_attn.q_proj
  - layers.60.self_attn.q_proj
  - layers.59.self_attn.q_proj
  - layers.48.self_attn.q_proj
  - layers.57.self_attn.q_proj
  - layers.70.self_attn.q_proj
  - layers.17.self_attn.q_proj
  - layers.67.self_attn.q_proj
  - layers.71.self_attn.q_proj
  - layers.51.self_attn.q_proj
  - layers.62.self_attn.q_proj
  - layers.58.self_attn.q_proj
  - layers.19.self_attn.q_proj
  - layers.13.self_attn.q_proj
  - lm.head
lr_scheduler: cosine
micro_batch_size: 4
model_type: AutoModelForCausalLM
num_epochs: 1
optimizer: paged_adamw_32bit
output_dir: ./outputs/Qwen
pad_to_sequence_len: true
resume_from_checkpoint: null
sample_packing: null
save_steps: null
save_strategy: null
saves_per_epoch: null
sequence_len: 4000
special_tokens:
  pad_token: <|endoftext|>
strict: false
tf32: false
tokenizer_type: AutoTokenizer
train_on_inputs: false
trust_remote_code: true
val_set_size: 0.001
wandb_entity: null
wandb_log_model: null
wandb_name: null
wandb_project: qwen-2-wo-8K
wandb_watch: null
warmup_steps: 20
weight_decay: 0.0
xformers_attention: null
