adapter: qlora
base_model: Qwen/Qwen2.5-14B-Instruct
bf16: auto
dataset_prepared_path: null
datasets:
- path: wasifis/54k_alpaca
  type: alpaca
debug: null
deepspeed: deepspeed_configs/zero2.json
early_stopping_patience: null
eval_table_size: null
evals_per_epoch: null
flash_attention: true
fp16: null
fsdp: null
fsdp_config: null
gradient_accumulation_steps: 4
gradient_checkpointing: true
group_by_length: false
learning_rate: 2.0e-05
load_in_4bit: true
load_in_8bit: false
local_rank: null
logging_steps: 1
lora_alpha: 64
lora_dropout: 0.05
lora_fan_in_fan_out: null
lora_model_dir: null
lora_r: 32
lora_target_linear: true
lora_target_modules:
  - layers.1.mlp.down_proj
  - layers.35.mlp.down_proj
  - layers.38.mlp.down_proj
  - layers.37.mlp.down_proj
  - layers.36.mlp.down_proj
  - layers.15.mlp.down_proj
  - layers.11.mlp.down_proj
  - layers.12.mlp.down_proj
  - layers.34.mlp.down_proj
  - layers.44.mlp.down_proj
  - layers.45.mlp.down_proj
  - layers.9.mlp.down_proj
  - layers.41.mlp.down_proj
  - layers.33.mlp.down_proj
  - layers.43.mlp.down_proj
  - layers.40.mlp.down_proj
  - layers.13.mlp.down_proj
  - layers.39.mlp.down_proj
  - layers.8.mlp.down_proj
  - layers.10.mlp.down_proj
  - layers.14.mlp.down_proj
  - layers.16.mlp.down_proj
  - layers.31.mlp.down_proj
  - layers.32.mlp.down_proj
  - layers.1.mlp.gate_proj
  - layers.44.mlp.gate_proj
  - layers.46.mlp.gate_proj
  - layers.45.mlp.gate_proj
  - layers.43.mlp.gate_proj
  - layers.47.mlp.gate_proj
  - layers.42.mlp.gate_proj
  - layers.32.mlp.gate_proj
  - layers.27.mlp.gate_proj
  - layers.33.mlp.gate_proj
  - layers.28.mlp.gate_proj
  - layers.39.mlp.gate_proj
  - layers.41.mlp.gate_proj
  - layers.40.mlp.gate_proj
  - layers.30.mlp.gate_proj
  - layers.29.mlp.gate_proj
  - layers.31.mlp.gate_proj
  - layers.26.mlp.gate_proj
  - layers.37.mlp.gate_proj
  - layers.10.mlp.gate_proj
  - layers.38.mlp.gate_proj
  - layers.12.mlp.gate_proj
  - layers.36.mlp.gate_proj
  - layers.13.mlp.gate_proj
  - layers.1.mlp.up_proj
  - layers.13.mlp.up_proj
  - layers.11.mlp.up_proj
  - layers.14.mlp.up_proj
  - layers.15.mlp.up_proj
  - layers.12.mlp.up_proj
  - layers.8.mlp.up_proj
  - layers.16.mlp.up_proj
  - layers.9.mlp.up_proj
  - layers.19.mlp.up_proj
  - layers.10.mlp.up_proj
  - layers.7.mlp.up_proj
  - layers.17.mlp.up_proj
  - layers.20.mlp.up_proj
  - layers.21.mlp.up_proj
  - layers.18.mlp.up_proj
  - layers.38.mlp.up_proj
  - layers.37.mlp.up_proj
  - layers.39.mlp.up_proj
  - layers.42.mlp.up_proj
  - layers.41.mlp.up_proj
  - layers.27.mlp.up_proj
  - layers.28.mlp.up_proj
  - layers.36.mlp.up_proj
  - layers.47.self_attn.k_proj
  - layers.39.self_attn.k_proj
  - layers.41.self_attn.k_proj
  - layers.37.self_attn.k_proj
  - layers.35.self_attn.k_proj
  - layers.44.self_attn.k_proj
  - layers.38.self_attn.k_proj
  - layers.14.self_attn.k_proj
  - layers.7.self_attn.k_proj
  - layers.12.self_attn.k_proj
  - layers.11.self_attn.k_proj
  - layers.32.self_attn.k_proj
  - layers.10.self_attn.k_proj
  - layers.8.self_attn.k_proj
  - layers.9.self_attn.k_proj
  - layers.6.self_attn.k_proj
  - layers.45.self_attn.k_proj
  - layers.42.self_attn.k_proj
  - layers.5.self_attn.k_proj
  - layers.40.self_attn.k_proj
  - layers.33.self_attn.k_proj
  - layers.0.self_attn.k_proj
  - layers.34.self_attn.k_proj
  - layers.13.self_attn.k_proj
  - layers.12.self_attn.o_proj
  - layers.5.self_attn.o_proj
  - layers.14.self_attn.o_proj
  - layers.16.self_attn.o_proj
  - layers.20.self_attn.o_proj
  - layers.13.self_attn.o_proj
  - layers.11.self_attn.o_proj
  - layers.4.self_attn.o_proj
  - layers.6.self_attn.o_proj
  - layers.19.self_attn.o_proj
  - layers.7.self_attn.o_proj
  - layers.18.self_attn.o_proj
  - layers.8.self_attn.o_proj
  - layers.38.self_attn.o_proj
  - layers.15.self_attn.o_proj
  - layers.17.self_attn.o_proj
  - layers.9.self_attn.o_proj
  - layers.10.self_attn.o_proj
  - layers.21.self_attn.o_proj
  - layers.28.self_attn.o_proj
  - layers.32.self_attn.o_proj
  - layers.35.self_attn.o_proj
  - layers.39.self_attn.o_proj
  - layers.3.self_attn.o_proj
  - layers.1.self_attn.q_proj
  - layers.2.self_attn.q_proj
  - layers.3.self_attn.q_proj
  - layers.44.self_attn.q_proj
  - layers.29.self_attn.q_proj
  - layers.45.self_attn.q_proj
  - layers.43.self_attn.q_proj
  - layers.32.self_attn.q_proj
  - layers.19.self_attn.q_proj
  - layers.38.self_attn.q_proj
  - layers.42.self_attn.q_proj
  - layers.34.self_attn.q_proj
  - layers.36.self_attn.q_proj
  - layers.40.self_attn.q_proj
  - layers.26.self_attn.q_proj
  - layers.20.self_attn.q_proj
  - layers.39.self_attn.q_proj
  - layers.28.self_attn.q_proj
  - layers.41.self_attn.q_proj
  - layers.35.self_attn.q_proj
  - layers.33.self_attn.q_proj
  - layers.25.self_attn.q_proj
  - layers.30.self_attn.q_proj
  - layers.27.self_attn.q_proj
  - layers.0.self_attn.v_proj
  - layers.7.self_attn.v_proj
  - layers.39.self_attn.v_proj
  - layers.31.self_attn.v_proj
  - layers.15.self_attn.v_proj
  - layers.10.self_attn.v_proj
  - layers.32.self_attn.v_proj
  - layers.41.self_attn.v_proj
  - layers.6.self_attn.v_proj
  - layers.33.self_attn.v_proj
  - layers.42.self_attn.v_proj
  - layers.29.self_attn.v_proj
  - layers.14.self_attn.v_proj
  - layers.9.self_attn.v_proj
  - layers.35.self_attn.v_proj
  - layers.38.self_attn.v_proj
  - layers.13.self_attn.v_proj
  - layers.30.self_attn.v_proj
  - layers.5.self_attn.v_proj
  - layers.34.self_attn.v_proj
  - layers.28.self_attn.v_proj
  - layers.37.self_attn.v_proj
  - layers.27.self_attn.v_proj
  - layers.11.self_attn.v_proj
  - lm.head
lr_scheduler: cosine
micro_batch_size: 2
model_type: AutoModelForCausalLM
num_epochs: 1
optimizer: paged_adamw_32bit
output_dir: ./outputs/Qwen2-7B
pad_to_sequence_len: true
resume_from_checkpoint: null
sample_packing: null
save_steps: null
save_strategy: null
saves_per_epoch: null
sequence_len: 8000
special_tokens:
  pad_token: <|endoftext|>
strict: false
tf32: false
tokenizer_type: AutoTokenizer
train_on_inputs: false
trust_remote_code: true
val_set_size: 0.001
wandb_entity: null
wandb_log_model: null
wandb_name: null
wandb_project: qwen-2-wo-8K
wandb_watch: null
warmup_steps: 20
weight_decay: 0.0
xformers_attention: null
